# Generated by Django 3.1.7 on 2021-12-31 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=200)),
                ('player_1_id', models.CharField(max_length=200)),
                ('player_2_id', models.CharField(max_length=200)),
                ('white_player_id', models.CharField(max_length=200)),
                ('black_player_id', models.CharField(max_length=200)),
                ('white_player_score', models.IntegerField(default=0)),
                ('black_player_score', models.IntegerField(default=0)),
                ('board', models.JSONField()),
                ('game_state', models.CharField(choices=[('GAME_SETUP', 'GAME_SETUP'), ('COLOR_CHOICE', 'COLOR_CHOICE'), ('GAME_RUNNING', 'GAME_RUNNING'), ('CLASH', 'CLASH'), ('SHOCK_MOVE', 'SHOCK_MOVE'), ('FINISHED', 'FINISHED')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200)),
                ('triangle_position', models.CharField(max_length=10)),
                ('circle_position', models.CharField(max_length=10)),
                ('move_timestamp', models.DateTimeField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kontranto_igra.game')),
            ],
        ),
    ]
