# Generated by Django 3.1.7 on 2021-12-31 16:14

from django.db import migrations, models
import kontranto_igra.models


class Migration(migrations.Migration):

    dependencies = [
        ('kontranto_igra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.JSONField(default=kontranto_igra.models.default_board),
        ),
    ]
