# Generated by Django 3.1.7 on 2022-01-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontranto_igra', '0002_auto_20211231_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game',
            new_name='game_id',
        ),
    ]
