# Generated by Django 3.1.7 on 2022-01-01 16:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kontranto_igra', '0003_auto_20220101_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='game',
            new_name='game_id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
