# Generated by Django 3.1.4 on 2021-01-05 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontranto_igra', '0003_auto_20210105_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='game_id',
        ),
        migrations.AddField(
            model_name='move',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kontranto_igra.game'),
        ),
    ]
