# Generated by Django 3.1.7 on 2022-01-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontranto_igra', '0004_auto_20220101_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='game_state',
            field=models.CharField(choices=[('GAME_SETUP', 'GAME_SETUP'), ('FINISHED', 'FINISHED'), ('COLOR_CHOICE', 'COLOR_CHOICE'), ('INITIAL_PLACEMENT', 'INITIAL_PLACEMENT'), ('GAME_RUNNING', 'GAME_RUNNING'), ('WAITING_WHITE_PLAYER_MOVE', 'WAITING_WHITE_PLAYER_MOVE'), ('WAITING_BLACK_PLAYER_MOVE', 'WAITING_BLACK_PLAYER_MOVE'), ('CLASH', 'CLASH'), ('SHOCK_MOVE', 'SHOCK_MOVE')], max_length=50),
        ),
    ]
