# Generated by Django 3.1.4 on 2021-01-05 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontranto_igra', '0005_auto_20210105_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_id',
            new_name='gamid',
        ),
    ]
