# Generated by Django 3.1.7 on 2022-01-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontranto_igra', '0005_auto_20220129_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player_1_color_choice',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='player_2_color_choice',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='game_state',
            field=models.CharField(choices=[('GAME_SETUP', 'GAME_SETUP'), ('FINISHED', 'FINISHED'), ('COLOR_CHOICE', 'COLOR_CHOICE'), ('WAITING_PLAYER_ONE_COLOR_CHOICE', 'WAITING_PLAYER_ONE_COLOR_CHOICE'), ('WAITING_PLAYER_TWO_COLOR_CHOICE', 'WAITING_PLAYER_TWO_COLOR_CHOICE'), ('INITIAL_PLACEMENT', 'INITIAL_PLACEMENT'), ('GAME_RUNNING', 'GAME_RUNNING'), ('WAITING_PLAYER_ONE_MOVE', 'WAITING_PLAYER_ONE_MOVE'), ('WAITING_PLAYER_TWO_MOVE', 'WAITING_PLAYER_TWO_MOVE'), ('CLASH', 'CLASH'), ('SHOCK_MOVE', 'SHOCK_MOVE')], max_length=50),
        ),
    ]
