# Generated by Django 3.1.7 on 2022-01-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontranto_igra', '0006_auto_20220130_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='black_player_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_state',
            field=models.CharField(choices=[('GAME_SETUP', 'GAME_SETUP'), ('FINISHED', 'FINISHED'), ('COLOR_CHOICE', 'COLOR_CHOICE'), ('INITIAL_PLACEMENT', 'INITIAL_PLACEMENT'), ('GAME_RUNNING', 'GAME_RUNNING'), ('WAITING_PLAYER_ONE_MOVE', 'WAITING_PLAYER_ONE_MOVE'), ('WAITING_PLAYER_TWO_MOVE', 'WAITING_PLAYER_TWO_MOVE'), ('CLASH', 'CLASH'), ('SHOCK_MOVE', 'SHOCK_MOVE')], max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_1_color_choice',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_2_color_choice',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_2_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='white_player_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
