# Generated by Django 3.1.7 on 2022-01-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kontranto_igra', '0007_auto_20220130_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='color',
            new_name='player_id',
        ),
    ]
