# Generated by Django 3.1.7 on 2022-03-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontranto_igra', '0008_auto_20220130_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='game_id',
            new_name='game',
        ),
        migrations.AddField(
            model_name='move',
            name='scoring_player_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='move',
            name='circle_position',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='move',
            name='triangle_position',
            field=models.JSONField(),
        ),
    ]
