# Generated by Django 3.0.9 on 2020-09-05 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=200)),
                ('white_player_id', models.CharField(max_length=200)),
                ('black_player_id', models.CharField(max_length=200)),
                ('white_score', models.IntegerField()),
                ('black_score', models.IntegerField()),
                ('white_triangle_position', models.CharField(max_length=200)),
                ('black_triangle_postition', models.CharField(max_length=200)),
                ('white_circle_position', models.CharField(max_length=200)),
                ('black_circle_position', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_triangle_position', models.CharField(max_length=200)),
                ('black_triangle_postion', models.CharField(max_length=200)),
                ('white_circle_position', models.CharField(max_length=200)),
                ('black_circle_position', models.CharField(max_length=200)),
                ('last_move_white_timestamp', models.DateTimeField()),
                ('last_move_black_timestamp', models.DateTimeField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kontranto_igra.Game')),
            ],
        ),
    ]
