# Generated by Django 3.1.4 on 2021-01-05 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontranto_igra', '0004_auto_20210105_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='move',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kontranto_igra.game'),
        ),
    ]
